const REQUEST_ACTIONS = {
    GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_FAILURE',
    PUT_SUCCESS: 'PUT_SUCCESS',
    PUT_FAILURE: 'PUT_FAILURE',
}

export default REQUEST_ACTIONS;